### ISSUE TITLE
Bounding box

### ISSUE THREAD

**Issue by nguyendohoangkhoi** [zhixuan-lin/SPACE#4]
Hello, I am working on your code. I have a question that how can i get bounding box like (x,y,x_max,y_max) of the model ?

**Comment by zhixuan-lin** [comment]
Hi @bentennyson9x, `z_where` [here](https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/model/space/fg.py#L236) refers to the bounding box. Its shape is `(B, G*G, 4)`, where `G*G` is the number of cells (e.g., `4*4`).  `z_where[:, :, :2]` gives the size of the object (normalized to `(0, 1)`)  and `z_where[:, :, 2:]` gives location (normalized to `(-1, 1)`). Since many of the cells won't contain valid objects, you also need `z_pres` [here](https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/model/space/fg.py#L237) to determine which cells contain objects.

To convert `z_where` and `z_pres`  (you should binarize `z_pres` before sending it in) into list of bounding boxes like `[[(y_min, y_max, x_min, x_max)]]` in pixel values, you can use the `convert_to_bbox` function [here](https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/eval/ap.py#L33).

**Comment by nguyendohoangkhoi** [comment]
Thanks for your help! I got it

**Comment by nguyendohoangkhoi** [comment]
I got an error "IndexError: The shape of the mask [256, 1] at index 1 does not match the shape of the indexed tensor [256, 4] at index 1" when I passed convert_to_boxes(log.z_where,log.z_pres, log.z_pres_prob) to the "convert_to_boxes" function. I checked again and realized that log.z_pres always has a shape (256,1) (because sigmoid) while log.z_where shape is ([256, 4] with [sx, sy, tx, ty]. Am I missing something?

**Comment by zhixuan-lin** [comment]
Ah sorry I forgot to mention this thing: you should squeeze `z_pres` and `z_pres_prob` from `(B, N, 1)` to `(B, N)` (i.e. `z_pres.squeeze(2)`) before sending them to `convert_to_boxes` as shown here
https://github.com/zhixuan-lin/SPACE/blob/e1eaf4ad387cd6f79df7fa9682333ea4da2072cc/src/eval/ap.py#L39-L40

**Comment by nguyendohoangkhoi** [comment]
I got bad values of the bounding box. I think it is due to the binarizing z_pres in 0 and 1 value. I don't know the threshold to do it. Can you help me. z_pres values are in this picture when I print it out
![image](https://user-images.githubusercontent.com/37859108/115166484-a74d2700-a0dd-11eb-8bc1-2b2f19e565aa.png)

**Comment by zhixuan-lin** [comment]
A simple `z_pres = z_pres > 0.5` should do. How did you binarize it? The result is supposed to be `ByteTensor` but what you show me seems to be `FloatTensor`.

**Comment by nguyendohoangkhoi** [comment]
Oh, I did it! Thank you very much. You save my day!

**Comment by zhixuan-lin** [comment]
You're welcome :)
